"""
GitHub PR comment + status check writer.

Companion to PRReviewerAgent. The agent generates compliance findings;
this service posts them as a GitHub comment + sets a check-run status
so the PR UI shows a pass/fail badge.

Requires:
- GITHUB_TOKEN env var with `pull_requests:write` and `checks:write`
  scopes on the medical-imaging-viewer repo.

Reference: GitHub REST API
- POST /repos/{owner}/{repo}/issues/{number}/comments
- POST /repos/{owner}/{repo}/check-runs
"""

import logging
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional

import httpx

logger = logging.getLogger(__name__)


def _api_base() -> str:
    return "https://api.github.com"


def _repo() -> str:
    from app.core.config import get_settings
    return get_settings().GITHUB_REPO


def _headers() -> Dict[str, str]:
    token = os.environ.get("GITHUB_TOKEN", "")
    h = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        h["Authorization"] = f"Bearer {token}"
    return h


def _format_comment(agent_summary: str, findings: List[Dict]) -> str:
    """Render agent findings as a GitHub-flavored markdown comment."""
    lines = [
        "## 🤖 MSTool-AI-QMS — PR Compliance Review",
        "",
        f"**Verdict:** {agent_summary}",
        "",
        "| Level | File | Clause | Issue | Suggested fix |",
        "| --- | --- | --- | --- | --- |",
    ]
    for f in findings[:25]:
        if not isinstance(f, dict):
            continue
        level = f.get("level", "info").upper()
        emoji = {"BLOCKING": "🛑", "WARNING": "⚠️", "INFO": "ℹ️"}.get(level, "•")
        lines.append(
            f"| {emoji} {level} "
            f"| `{f.get('file', '?')}` "
            f"| {f.get('clause', '?')} "
            f"| {(f.get('issue', '') or '').replace('|', '/')[:140]} "
            f"| {(f.get('suggested_fix', '') or '').replace('|', '/')[:120]} |"
        )
    lines += [
        "",
        "_Generated by MSTool-AI-QMS PR Reviewer agent (Claude Sonnet 4.5)._",
        "_Citations and approval flow at https://mstool-ai-qms.web.app/agents._",
    ]
    return "\n".join(lines)


def post_pr_comment(pr_number: int, body: str) -> Dict:
    """Post a comment to a PR. Returns {posted, comment_id, error?}."""
    url = f"{_api_base()}/repos/{_repo()}/issues/{pr_number}/comments"
    try:
        with httpx.Client(timeout=20) as client:
            resp = client.post(url, headers=_headers(), json={"body": body})
            if resp.status_code in (200, 201):
                return {"posted": True, "comment_id": resp.json().get("id")}
            return {"posted": False, "error": f"{resp.status_code}: {resp.text[:200]}"}
    except Exception as e:
        return {"posted": False, "error": str(e)}


def create_check_run(head_sha: str, name: str, conclusion: str,
                       summary: str, text: str = "") -> Dict:
    """Create a GitHub Check Run for the PR's head commit.

    `conclusion` ∈ success | failure | neutral | action_required.
    """
    url = f"{_api_base()}/repos/{_repo()}/check-runs"
    payload = {
        "name": name,
        "head_sha": head_sha,
        "status": "completed",
        "conclusion": conclusion,
        "completed_at": datetime.now(timezone.utc).isoformat(),
        "output": {
            "title": "MSTool-AI-QMS Compliance Review",
            "summary": summary,
            "text": text or summary,
        },
    }
    try:
        with httpx.Client(timeout=20) as client:
            resp = client.post(url, headers=_headers(), json=payload)
            if resp.status_code in (200, 201):
                return {"created": True, "id": resp.json().get("id")}
            return {"created": False, "error": f"{resp.status_code}: {resp.text[:200]}"}
    except Exception as e:
        return {"created": False, "error": str(e)}


def publish_pr_review(pr_number: Optional[int], head_sha: Optional[str],
                       agent_summary: str, findings: List[Dict]) -> Dict:
    """High-level: post comment + create check run from a PR Reviewer run."""
    out = {"pr_number": pr_number, "head_sha": head_sha,
            "comment": None, "check_run": None}

    has_blocking = any(
        isinstance(f, dict) and f.get("level") == "blocking"
        for f in (findings or [])
    )
    conclusion = "failure" if has_blocking else "neutral" if findings else "success"

    if pr_number:
        body = _format_comment(agent_summary, findings)
        out["comment"] = post_pr_comment(pr_number, body)

    if head_sha:
        out["check_run"] = create_check_run(
            head_sha=head_sha,
            name="MSTool-AI-QMS / PR Reviewer",
            conclusion=conclusion,
            summary=agent_summary,
            text=_format_comment(agent_summary, findings)[:60000],
        )

    return out
