import { useState } from 'react';
import {
  BookOpen, ChevronDown, ChevronRight, FileText, Users, ShieldCheck,
  ClipboardCheck, Sparkles, MessageSquare,
} from 'lucide-react';

/* ═══════════════════════════════════════════════════════════════
   GUIDE PAGE — Complete operational reference for MSTool-AI-QMS.

   Rebuilt to reflect ALL current capabilities (10 agents, baselines,
   insights, MCP gateway, WORM ledger, AI drafts, SBOM export, etc.)
   and to work properly in both light and dark mode.

   Audience: Developers, QA, QMS Managers, Clinical Advisors, Admins.
   ═══════════════════════════════════════════════════════════════ */

/* ─── Data ─── */
const PAGES_GUIDE = [
  {
    name: 'Dashboard', path: '/', color: '#0EA5E9',
    purpose: 'Real-time compliance overview with trend charts, CI status, and dual scoring (Health Score + Audit Verdict).',
    keyActions: [
      'Check the 4-line trend chart for regressions',
      'Review "Requires Attention" cards for pending fixes',
      'Expand each Responsibility Area to drill into per-check evidence',
      'Click "Why two scores?" to understand Health vs Audit methodology',
    ],
  },
  {
    name: 'Trends', path: '/trends', color: '#0EA5E9',
    purpose: 'Time-series analytics — compliance score over 7/30/90/365 days with event overlays.',
    keyActions: [
      'Select time range (7d → 365d)',
      'Hover data points to see what happened on that day',
      'Watch for regression alerts from the Prophet sentinel',
    ],
  },
  {
    name: 'Activity', path: '/activity', color: '#0EA5E9',
    purpose: 'WORM (Write-Once-Read-Many) audit trail — every mutation is hash-chained (21 CFR Part 11 §11.10(e)).',
    keyActions: [
      'Filter by user, resource type, or time window',
      'Verify the ledger head hash matches the expected sequence',
      'Check the Firebase project verification badge (must be "mstool-ai-qms")',
    ],
  },
  {
    name: 'Forms', path: '/forms', color: '#8B5CF6',
    purpose: 'Create, fill, sign, and approve regulatory evidence records. 11 templates covering IEC 62304 + ISO 13485.',
    keyActions: [
      'Select a template (TPL-01 to TPL-11) → form opens in Draft',
      'Fill required fields → Save → Submit for Review',
      'QMS Manager clicks Approve → form is locked with e-signature',
      'Look for "✨ AI-drafted" badge — those were auto-generated by the Gap Closer agent',
    ],
  },
  {
    name: 'Audit', path: '/audit', color: '#8B5CF6',
    purpose: 'Simulate a Notified Body audit against 20 IEC 62304 clauses with real repository evidence.',
    keyActions: [
      'Click ▶ Full IEC 62304 Audit (takes ~30s)',
      'Review clause-by-clause verdicts: strong/adequate/weak/missing',
      'For failed clauses → click "Create Form →" to generate evidence',
      'Check the calculation formula at the top: (13×100 + 3×75 + 2×40 + 2×0) ÷ 2000',
    ],
  },
  {
    name: 'Releases', path: '/releases', color: '#8B5CF6',
    purpose: 'Immutable QMS baselines for CE Mark / FDA submission. E-signed, hash-protected, diffable.',
    keyActions: [
      'Create Baseline → captures entire QMS state (scores, traceability, SOUP, activity)',
      'Sign a baseline with 21 CFR Part 11 §11.50 e-signature',
      'Compare two baselines → see what changed in scores, SOUP, traceability',
      'Export Submission Package ZIP → one-click FDA/Notified Body bundle',
    ],
  },
  {
    name: 'Traceability', path: '/traceability', color: '#10B981',
    purpose: 'Bidirectional requirement traceability matrix + interactive graph (IEC 62304 §5.1.1).',
    keyActions: [
      'Check Forward % (REQ→Test) and Backward % (Test→REQ) in the banner',
      'Toggle between Matrix RTM view (auditor) and Graph view (developer)',
      'Filter by category (FUNC/SAFE/PERF/SEC) or status (complete/partial/uncovered)',
      'Orange "suspect" badges = code changed recently, re-verify trace chain',
      'Export CSV for auditor documentation',
    ],
  },
  {
    name: 'SOUP', path: '/soup', color: '#10B981',
    purpose: 'Software of Unknown Provenance — 92 dependencies with CVE scanning, SBOM export, AI review drafts.',
    keyActions: [
      'Click "Scan for CVEs" → results persisted in scan history',
      'Download "SBOM (CycloneDX)" → FDA-accepted format for 510(k)',
      'Click any package → modal with anomalies, EOL data, CVEs, AI review draft',
      'Click "✨ AI Review Drafts" → Haiku generates §8.1.2 reviews for Class C deps',
      'Check "Unpinned Class C" alert banner (IEC 62304 §5.1.7 violation)',
    ],
  },
  {
    name: 'Doc Sync', path: '/docsync', color: '#10B981',
    purpose: 'Document lifecycle management — review status, freshness, change history, completeness (ISO 13485 §4.2.4).',
    keyActions: [
      'Filter by standard or search by document name',
      'Expand urgency groups: Never Reviewed → Modified Since Review → Overdue → Current',
      'Export CSV for auditor review',
    ],
  },
  {
    name: 'Agents', path: '/agents', color: '#06B6D4',
    purpose: '10 validated Claude AI agents that analyze, draft, and recommend — every output cited and approvable.',
    keyActions: [
      'Click "Run" on any agent to invoke it on demand',
      'Review findings + citations in the run detail modal',
      'Click "Sign & Approve" for agents that require human sign-off',
      'Check the Skills panel → 3 knowledge bundles (IEC 62304, ISO 14971, SaMD Brain MRI)',
      'Click "Run canaries" → weekly drift detection for AI quality',
      'Click "Generate PCCP" → FDA-format change plan for model updates',
    ],
  },
  {
    name: 'Insights', path: '/insights', color: '#06B6D4',
    purpose: 'Predictive ML + AI validation: gap attribution, clause-level audit forecast, commit impact, SaMD scanner.',
    keyActions: [
      'Review "What\'s costing your score?" waterfall → fix top gaps first',
      'Check clause P(fail) heatmap → at-risk clauses get priority',
      'Review commit impact → which REQs/tests/hazards each commit affected',
      'Download "AI Validation Dossier" → IQ/OQ/PQ + PCCP per agent (FDA submission)',
      'Check suspect links + missing trace link predictions',
    ],
  },
];

const AGENTS_GUIDE = [
  { name: 'Traceability', tier: 'Haiku', trigger: 'On demand / PR', what: 'Flags commits missing REQ-ID references; proposes trace links', signoff: false },
  { name: 'SOUP Monitor', tier: 'Haiku', trigger: 'Daily 3am + on demand', what: 'Analyzes CVEs against your specific dependency usage', signoff: false },
  { name: 'PR Reviewer', tier: 'Sonnet', trigger: 'On PR open/sync', what: 'Reviews PRs against IEC 62304 §5.5-5.8; posts to GitHub', signoff: true },
  { name: 'Doc Drift', tier: 'Sonnet', trigger: 'On demand', what: 'Detects drift between code and SRS/SDS/RMF; proposes edits', signoff: true },
  { name: 'CAPA Drafter', tier: 'Sonnet', trigger: 'On demand', what: 'Drafts 5-whys + corrective + preventive action per 21 CFR 820.100', signoff: true },
  { name: 'Clause Chat', tier: 'Haiku', trigger: 'User question', what: 'Answers compliance questions with citations to commits/clauses', signoff: false },
  { name: 'Audit Prep', tier: 'Opus 4.6', trigger: 'On demand', what: 'Whole-project audit prep + draft responses to auditor questions', signoff: true },
  { name: 'Risk Analyst', tier: 'Sonnet', trigger: 'On demand', what: 'Proposes new hazards from Class C code diffs per ISO 14971', signoff: true },
  { name: 'Regulatory Watch', tier: 'Sonnet', trigger: 'Weekly Mon 6am', what: 'Digest of FDA/EU/IEC updates relevant to our SaMD scope', signoff: false },
  { name: 'Gap Closer', tier: 'Opus 4.6', trigger: 'On demand', what: 'Detects gap → drafts form → persists as draft → routes for e-sign', signoff: true },
];

const TEMPLATE_REF = [
  { id: 'TPL-01', title: 'Problem Report', clause: 'IEC 62304 §9', when: 'Bug found', who: 'Developer' },
  { id: 'TPL-02', title: 'Release Checklist', clause: 'IEC 62304 §5.8', when: 'Before release', who: 'QA + QMS' },
  { id: 'TPL-03', title: 'Code Review Checklist', clause: 'IEC 62304 §5.5.3', when: 'Every Class C review', who: 'Developer' },
  { id: 'TPL-04', title: 'Risk Control Verification', clause: 'ISO 14971 §7.4', when: 'Verifying controls', who: 'QA' },
  { id: 'TPL-05', title: 'Design Review Record', clause: 'IEC 62304 §5.3', when: 'Architecture review', who: 'Lead' },
  { id: 'TPL-06', title: 'Test Execution Report', clause: 'IEC 62304 §5.5.5', when: 'Test session', who: 'QA' },
  { id: 'TPL-07', title: 'SOUP Vulnerability Review', clause: 'IEC 81001-5-1 §5.3.12', when: 'Monthly', who: 'Security' },
  { id: 'TPL-08', title: 'Serious Incident Report', clause: 'EU MDR Article 87', when: 'Safety incident', who: 'Clinical' },
  { id: 'TPL-09', title: 'Change Control Record', clause: 'IEC 62304 §8', when: 'System change', who: 'Developer' },
  { id: 'TPL-10', title: 'Quality Gate Approval', clause: 'IEC 62304 §5.1', when: 'Phase gate', who: 'QMS' },
  { id: 'TPL-11', title: 'Document Approval', clause: 'ISO 13485 §4.2.4', when: 'Doc revision', who: 'QMS' },
];

const CLAUSE_MAP = [
  ['5.1', 'Software Development Planning', 'Dashboard + TPL-10'],
  ['5.2', 'Software Requirements Analysis', 'Traceability + TPL-05'],
  ['5.3', 'Software Architectural Design', 'Traceability + TPL-05'],
  ['5.4', 'Software Detailed Design', 'Traceability + TPL-05'],
  ['5.5', 'Unit Implementation & Verification', 'Dashboard (tests) + TPL-03/06 + PR Reviewer agent'],
  ['5.6', 'Integration Testing', 'Dashboard (CI) + TPL-06'],
  ['5.7', 'System Testing', 'TPL-06 + Audit simulation'],
  ['5.8', 'Software Release', 'TPL-02 + Releases (baselines)'],
  ['6.1', 'Maintenance Planning', 'Doc Sync + Regulatory Watch agent'],
  ['6.2', 'Problem/Modification Analysis', 'TPL-01 + CAPA Drafter agent'],
  ['7.1', 'Risk Analysis', 'Traceability + Risk Analyst agent'],
  ['7.2', 'Risk Control', 'Traceability + TPL-04'],
  ['7.3', 'Risk Control Verification', 'TPL-04 + Insights (predict)'],
  ['7.4', 'Risk Management of Changes', 'TPL-09 + suspect links'],
  ['8.1', 'Configuration Identification', 'SOUP + SBOM CycloneDX export'],
  ['8.2', 'Change Control', 'TPL-09 + Activity WORM ledger'],
  ['8.3', 'Configuration Status', 'Dashboard + Releases + Activity'],
  ['9.1', 'Problem Reports', 'TPL-01 + CAPA Drafter agent'],
  ['9.2', 'Investigation', 'TPL-01 (root cause) + Insights (impact)'],
  ['9.3', 'Advisory Notices', 'TPL-08 + Regulatory Watch agent'],
];

const AUDIT_CHECKLIST = [
  'Full Audit score ≥95% (run on Audit page)',
  'All Traceability orphans resolved or justified',
  'All Class C forms signed and approved',
  'SOUP CVE scan run within last 30 days (check Scan History tab)',
  'SBOM CycloneDX exported and attached to submission',
  'All regulatory documents reviewed (Doc Sync — no "Never Reviewed" items)',
  'All hazards have verified risk controls (TPL-04)',
  'Release baseline created and signed for current version',
  'AI Validation Dossier exported from Insights page',
  'Activity WORM ledger verified (Admin → /system/ledger/verify)',
  'PDF exports of all critical forms available',
  'Team can demo live QMS usage to auditor',
];

const ROLES_DATA = [
  { role: 'Admin', color: '#EF4444', perms: 'Full access. System config, ledger verify, user management, all agent invocations.', who: 'Project Lead' },
  { role: 'QMS Manager', color: '#8B5CF6', perms: 'Audits, baselines, form approval, AI review draft generation, PCCP generation.', who: 'Quality Manager' },
  { role: 'Developer', color: '#3B82F6', perms: 'Forms, agents (invoke + approve), traceability, dashboard. No user management.', who: 'Software Engineer' },
  { role: 'QA', color: '#10B981', perms: 'Forms, agents, test reports, audit runs. No baseline signing.', who: 'QA Engineer' },
  { role: 'Clinical Advisor', color: '#F59E0B', perms: 'View reports, sign clinical forms (TPL-08), review risk controls, Clause Chat.', who: 'Clinician / MD' },
  { role: 'Viewer', color: '#64748B', perms: 'Read-only access to dashboards, traceability, and reports. Cannot invoke agents.', who: 'Auditor / Stakeholder' },
];

const FAQ = [
  { q: 'Dashboard charts are empty', a: 'Snapshots are captured hourly by Cloud Scheduler. Trigger one manually: POST /api/v1/cron/snapshot. Or just wait — the Dashboard also stores a snapshot every time it loads.' },
  { q: 'Audit shows "Audit failed"', a: 'Click "Dismiss" to clear the old error, then run a new audit. The most common cause was a GitHub rate limit — now fixed with authenticated token (5000 req/hr).' },
  { q: 'Agent returned a stub answer', a: 'ANTHROPIC_API_KEY is missing or invalid on Cloud Run. Admin must re-set it via gcloud run services update.' },
  { q: 'E-signature shows "hmac_sha256_dev"', a: 'Cloud KMS signing key not configured. The HMAC fallback works for internal use but is not FDA-grade. See DEPLOYMENT.md → "Bootstrap a Cloud KMS signing key".' },
  { q: 'How do I connect my IDE to the QMS?', a: 'POST /api/v1/mcp with JSON-RPC 2.0 envelope. 7 read-only tools: compliance.score, traceability.stats, baselines.latest, soup.summary, gaps.top, audit.run-status, predict.clauses.' },
  { q: 'What model does each agent use?', a: 'Haiku 4.5 for pattern matching (Traceability, SOUP, Clause Chat). Sonnet 4.5 for reasoning (PR Review, Doc Drift, CAPA, Risk, Regulatory). Opus 4.6 for whole-project analysis (Audit Prep, Gap Closer).' },
  { q: 'How is the Health Score different from the Audit Verdict?', a: 'Health Score (Dashboard) is continuous telemetry — 88% auth coverage = 88 pts. Audit Verdict (Audit page) is discrete auditor grading — same 88% = "adequate" = 75 pts. Both are correct, different lenses. Click "Why two scores?" on Dashboard.' },
  { q: 'Where is the SBOM?', a: 'SOUP page → header → "SBOM (CycloneDX)" button. Downloads a .cdx.json in CycloneDX 1.5 format (FDA 510(k) accepted).' },
];

/* ─── Component ─── */
export default function GuidePage() {
  const [open, setOpen] = useState<string>('pages');
  const toggle = (id: string) => setOpen(open === id ? '' : id);

  const Section = ({ id, title, icon: Icon, children }: { id: string; title: string; icon: any; children: React.ReactNode }) => {
    const isOpen = open === id;
    return (
      <div className="rounded-2xl overflow-hidden transition-all"
        style={{ background: 'var(--card-bg)', border: `1px solid ${isOpen ? 'rgba(14,165,233,0.25)' : 'var(--card-border)'}`, boxShadow: isOpen ? '0 4px 20px rgba(14,165,233,0.06)' : 'var(--card-shadow)' }}>
        <button onClick={() => toggle(id)} className="w-full flex items-center gap-4 px-5 py-4 text-left">
          <div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0" style={{ background: 'rgba(14,165,233,0.08)' }}>
            <Icon size={18} style={{ color: '#0EA5E9' }} />
          </div>
          <span className="flex-1 text-[15px] font-bold" style={{ color: 'var(--text-primary)' }}>{title}</span>
          {isOpen ? <ChevronDown size={16} style={{ color: 'var(--text-muted)' }} /> : <ChevronRight size={16} style={{ color: 'var(--text-muted)' }} />}
        </button>
        {isOpen && <div className="px-5 pb-5" style={{ borderTop: '1px solid var(--border-subtle)' }}>{children}</div>}
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Banner */}
      <div className="rounded-2xl p-5 flex items-center gap-4"
        style={{ background: 'linear-gradient(135deg, rgba(14,165,233,0.08), rgba(139,92,246,0.04))', border: '1px solid rgba(14,165,233,0.15)' }}>
        <div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ background: 'rgba(14,165,233,0.12)' }}>
          <BookOpen size={24} style={{ color: '#0EA5E9' }} />
        </div>
        <div>
          <span className="text-[18px] font-bold" style={{ color: 'var(--text-primary)' }}>MSTool-AI-QMS — Complete Reference</span>
          <p className="text-[12px] mt-0.5" style={{ color: 'var(--text-muted)' }}>
            12 pages · 10 AI agents · 121 API endpoints · 11 form templates · 20 IEC 62304 clauses
          </p>
          <div className="flex items-center gap-2 mt-1 flex-wrap">
            {['IEC 62304', 'ISO 13485', 'ISO 14971', 'IEC 81001-5-1', 'EU MDR', '21 CFR Part 11', 'FDA PCCP'].map(s => (
              <span key={s} className="text-[9px] font-bold font-mono px-1.5 py-0.5 rounded" style={{ background: 'var(--bg-tertiary)', color: 'var(--text-muted)' }}>{s}</span>
            ))}
          </div>
        </div>
      </div>

      {/* Sections */}
      <div className="space-y-3">

        {/* 1 — Pages Guide */}
        <Section id="pages" title="How to Use Each Page (12 pages)" icon={BookOpen}>
          <div className="pt-3 space-y-2">
            {PAGES_GUIDE.map(p => (
              <div key={p.path} className="rounded-xl p-3.5" style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)' }}>
                <div className="flex items-center gap-2 mb-1.5">
                  <div className="w-2 h-2 rounded-full" style={{ background: p.color }} />
                  <span className="text-[13px] font-bold" style={{ color: 'var(--text-primary)' }}>{p.name}</span>
                  <code className="text-[9px] font-mono px-1.5 py-0.5 rounded" style={{ background: 'var(--card-bg)', color: 'var(--text-muted)' }}>{p.path}</code>
                </div>
                <p className="text-[11px] mb-2" style={{ color: 'var(--text-secondary)' }}>{p.purpose}</p>
                <div className="space-y-1">
                  {p.keyActions.map((a, i) => (
                    <div key={i} className="flex items-start gap-2 text-[10px]" style={{ color: 'var(--text-muted)' }}>
                      <span className="w-4 h-4 rounded flex items-center justify-center shrink-0 text-[8px] font-bold" style={{ background: `${p.color}15`, color: p.color }}>{i + 1}</span>
                      <span>{a}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Section>

        {/* 2 — AI Agents */}
        <Section id="agents" title="10 AI Agents — When and How" icon={Sparkles}>
          <div className="pt-3">
            <p className="text-[11px] mb-3" style={{ color: 'var(--text-muted)' }}>
              Every agent is a validated SOUP component (IEC 62304 §5.3.3) with pinned Claude model version, constitutional guardrails,
              and drift monitoring. Outputs requiring human sign-off are marked below.
            </p>
            <div className="space-y-1.5">
              {AGENTS_GUIDE.map(a => (
                <div key={a.name} className="flex items-center gap-3 p-2.5 rounded-lg" style={{ background: 'var(--bg-tertiary)' }}>
                  <span className="text-[10px] font-bold px-1.5 py-0.5 rounded shrink-0"
                    style={{ background: a.tier === 'Opus 4.6' ? 'rgba(236,72,153,0.12)' : a.tier === 'Sonnet' ? 'rgba(139,92,246,0.12)' : 'rgba(6,182,212,0.12)',
                             color: a.tier === 'Opus 4.6' ? '#EC4899' : a.tier === 'Sonnet' ? '#8B5CF6' : '#06B6D4' }}>
                    {a.tier}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1.5">
                      <span className="text-[12px] font-semibold" style={{ color: 'var(--text-primary)' }}>{a.name}</span>
                      {a.signoff && (
                        <span className="text-[8px] font-bold px-1 py-0.5 rounded" style={{ background: 'rgba(245,158,11,0.12)', color: '#F59E0B' }}>SIGN-OFF</span>
                      )}
                    </div>
                    <p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{a.what}</p>
                  </div>
                  <span className="text-[9px] font-mono shrink-0" style={{ color: 'var(--text-muted)' }}>{a.trigger}</span>
                </div>
              ))}
            </div>
          </div>
        </Section>

        {/* 3 — Role Workflows */}
        <Section id="roles" title="Roles, Permissions & Daily Workflow" icon={Users}>
          <div className="pt-3 space-y-4">
            {ROLES_DATA.map(r => (
              <div key={r.role} className="rounded-xl p-3.5" style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)' }}>
                <div className="flex items-center gap-2 mb-1">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ background: r.color }} />
                  <span className="text-[13px] font-bold" style={{ color: 'var(--text-primary)' }}>{r.role}</span>
                  <span className="text-[10px] ml-auto" style={{ color: 'var(--text-muted)' }}>Typical: {r.who}</span>
                </div>
                <p className="text-[11px]" style={{ color: 'var(--text-secondary)' }}>{r.perms}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* 4 — Templates */}
        <Section id="templates" title="Form Templates (TPL-01 to TPL-11)" icon={FileText}>
          <div className="pt-3 overflow-x-auto">
            <table className="w-full text-[11px]">
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>ID</th>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>Title</th>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>Clause</th>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>When</th>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>Who</th>
                </tr>
              </thead>
              <tbody>
                {TEMPLATE_REF.map(t => (
                  <tr key={t.id} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                    <td className="px-3 py-2"><code className="font-mono font-bold" style={{ color: 'var(--accent-teal)' }}>{t.id}</code></td>
                    <td className="px-3 py-2 font-medium" style={{ color: 'var(--text-primary)' }}>{t.title}</td>
                    <td className="px-3 py-2 text-[10px]" style={{ color: 'var(--text-muted)' }}>{t.clause}</td>
                    <td className="px-3 py-2" style={{ color: 'var(--text-secondary)' }}>{t.when}</td>
                    <td className="px-3 py-2" style={{ color: 'var(--text-muted)' }}>{t.who}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>

        {/* 5 — IEC 62304 Clause Mapping */}
        <Section id="clauses" title="IEC 62304 → QMS Feature Mapping (20 clauses)" icon={ShieldCheck}>
          <div className="pt-3 overflow-x-auto">
            <table className="w-full text-[11px]">
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>Clause</th>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>Title</th>
                  <th className="text-left px-3 py-2 text-[9px] font-bold uppercase tracking-wider" style={{ color: 'var(--text-muted)' }}>QMS Feature</th>
                </tr>
              </thead>
              <tbody>
                {CLAUSE_MAP.map(([clause, title, feature]) => (
                  <tr key={clause} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                    <td className="px-3 py-2"><code className="font-mono font-bold" style={{ color: 'var(--accent-teal)' }}>{clause}</code></td>
                    <td className="px-3 py-2" style={{ color: 'var(--text-primary)' }}>{title}</td>
                    <td className="px-3 py-2" style={{ color: 'var(--text-secondary)' }}>{feature}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>

        {/* 6 — Audit Checklist */}
        <Section id="checklist" title="Pre-Audit Checklist (12 items)" icon={ClipboardCheck}>
          <div className="pt-3 rounded-xl p-4" style={{ background: 'rgba(245,158,11,0.04)', border: '1px solid rgba(245,158,11,0.15)' }}>
            <p className="text-[12px] font-bold mb-3" style={{ color: '#D97706' }}>Complete ALL items before an external audit</p>
            <div className="space-y-2">
              {AUDIT_CHECKLIST.map((item, i) => (
                <label key={i} className="flex items-start gap-3 text-[11px] cursor-pointer" style={{ color: 'var(--text-secondary)' }}>
                  <input type="checkbox" className="mt-0.5 rounded" />
                  <span>{item}</span>
                </label>
              ))}
            </div>
          </div>
        </Section>

        {/* 7 — FAQ */}
        <Section id="faq" title="Frequently Asked Questions" icon={MessageSquare}>
          <div className="pt-3 space-y-2">
            {FAQ.map((f, i) => (
              <div key={i} className="rounded-xl p-3.5" style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)' }}>
                <p className="text-[12px] font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>Q: {f.q}</p>
                <p className="text-[11px]" style={{ color: 'var(--text-secondary)' }}>{f.a}</p>
              </div>
            ))}
          </div>
        </Section>

      </div>

      {/* Footer */}
      <div className="rounded-xl p-3 text-center text-[10px]" style={{ color: 'var(--text-muted)', background: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)' }}>
        Full technical roadmap: <code style={{ color: 'var(--accent-teal)' }}>docs/MASTER_PLAN.md</code> ·
        Deployment: <code style={{ color: 'var(--accent-teal)' }}>docs/DEPLOYMENT.md</code> ·
        User Guide: <code style={{ color: 'var(--accent-teal)' }}>docs/USER_GUIDE.md</code> ·
        Costs: <code style={{ color: 'var(--accent-teal)' }}>docs/COSTS.md</code>
      </div>
    </div>
  );
}
